name: PR Quality Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: rm -f package-lock.json && npm install

      - name: Build packages
        run: npm run build --workspace=minuta --workspace=minuta-react --workspace=minuta-vue --workspace=minuta-svelte

      - name: Run tests
        run: npm run test
        env:
          TZ: UTC
